#![allow(rustdoc::private_intra_doc_links)]

#[path = "../../../examples/aabb/lib.rs"]
pub mod aabb;
#[path = "../../../examples/animating_pi/lib.rs"]
pub mod animating_pi;
#[path = "../../../examples/arc/lib.rs"]
pub mod arc;
#[path = "../../../examples/arc_between_points/lib.rs"]
pub mod arc_between_points;
#[path = "../../../examples/basic/lib.rs"]
pub mod basic;
#[path = "../../../examples/bubble_sort/lib.rs"]
pub mod bubble_sort;
#[path = "../../../examples/cloth_wrap/lib.rs"]
pub mod cloth_wrap;
#[path = "../../../examples/composable_choreography/lib.rs"]
pub mod composable_choreography;
#[path = "../../../examples/ellipse/lib.rs"]
pub mod ellipse;
#[path = "../../../examples/extract_vitem_visualize/lib.rs"]
pub mod extract_vitem_visualize;
#[path = "../../../examples/getting_started0/lib.rs"]
pub mod getting_started0;
#[path = "../../../examples/getting_started1/lib.rs"]
pub mod getting_started1;
#[path = "../../../examples/getting_started2/lib.rs"]
pub mod getting_started2;
#[path = "../../../examples/hanoi/lib.rs"]
pub mod hanoi;
#[path = "../../../examples/hello_ranim/lib.rs"]
pub mod hello_ranim;
#[path = "../../../examples/iterative_spring/lib.rs"]
pub mod iterative_spring;
#[path = "../../../examples/mesh_morph/lib.rs"]
pub mod mesh_morph;
#[path = "../../../examples/midi_visualizer/lib.rs"]
pub mod midi_visualizer;
#[path = "../../../examples/nbody/lib.rs"]
pub mod nbody;
#[path = "../../../examples/output_formats/lib.rs"]
pub mod output_formats;
#[path = "../../../examples/palettes/lib.rs"]
pub mod palettes;
#[path = "../../../examples/perlin_terrain/lib.rs"]
pub mod perlin_terrain;
#[path = "../../../examples/perspective_blend/lib.rs"]
pub mod perspective_blend;
#[path = "../../../examples/ranim_logo/lib.rs"]
pub mod ranim_logo;
#[path = "../../../examples/regular_polygon/lib.rs"]
pub mod regular_polygon;
#[path = "../../../examples/selective_sort/lib.rs"]
pub mod selective_sort;
#[path = "../../../examples/solar_system/lib.rs"]
pub mod solar_system;
#[path = "../../../examples/test/lib.rs"]
pub mod test;
#[path = "../../../examples/tetrahedron_spheres/lib.rs"]
pub mod tetrahedron_spheres;
#[path = "../../../examples/text_item/lib.rs"]
pub mod text_item;
#[path = "../../../examples/typst_timer/lib.rs"]
pub mod typst_timer;

mod midi {
    pub(crate) use crate::midi_visualizer::midi::*;
}
