[package]
name = "ranim-examples"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
app = ["ranim/app"]

[target.'cfg(target_family = "wasm")'.dependencies]
ranim = { workspace = true, features = ["app"] }

[lib]
crate-type = ["rlib", "cdylib"] # use cdylib to produce .wasm file

[dependencies]
ranim.workspace = true
ranim-macros.workspace = true
rand = "0.9.2"
rand_chacha = "0.9.0"
wasm-bindgen = "0.2.100"

[package.metadata.release]
tag = false

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs_dep"]
rustdoc-args = ["--cfg", "docsrs_dep", "--html-in-header", "docs-rs/header.html"]

