[package]
name = "ranim-macros"
description = "macros for ranim"
version.workspace = true
edition.workspace = true
license.workspace = true

repository.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.20.3"
heck = "0.4.1"
proc-macro2 = "1.0.70"
quote = "1.0.33"
syn = { version = "2.0.39", features = ["full"] }
paste = "1.0.14"

[package.metadata.release]
tag = false
