[package]
name = "ranim-anims"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ranim-core.workspace = true
log.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.release]
tag = false